=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/entity_scheme.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="amasty_report_builder_entities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="entity" type="entityType" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="entityType">
        <xs:annotation>
            <xs:documentation>
                Amasty Custom Report Builder Entity Declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element type="xs:string" name="title" minOccurs="0" />
            <xs:element type="xs:string" name="main_table" minOccurs="0" />
            <xs:element type="xs:boolean" name="hidden" minOccurs="0" />

            <xs:element name="columns" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="column" type="columnType" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="relations" minOccurs="0" >
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="relation" type="relationType" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="expressions" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="expression" type="expressionType" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="eav" type="xs:boolean" />
        <xs:attribute name="primary" type="xs:boolean" />
    </xs:complexType>

    <xs:complexType name="columnType">
        <xs:annotation>
            <xs:documentation>
                Amasty Custom Report Builder Column Declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="title" minOccurs="0" />
            <xs:element type="xs:string" name="type" minOccurs="0" />
            <xs:element type="xs:string" name="aggregation_type" minOccurs="0" />
            <xs:element type="xs:string" name="source_model" minOccurs="0" />
            <xs:element type="xs:string" name="ui_grid_class" minOccurs="0" />
            <xs:element type="xs:string" name="hidden" minOccurs="0" />
            <xs:element type="optionType" name="options" minOccurs="0" />
            <xs:element type="xs:string" name="link" minOccurs="0" />
            <xs:element type="xs:string" name="custom_expression" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="columnType">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="default" />
                    <xs:enumeration value="eav" />
                    <xs:enumeration value="foreign" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="useForPeriod" type="xs:boolean" />
        <xs:attribute name="frontendModel" type="xs:string" />
        <xs:attribute name="primary" type="xs:boolean" />
    </xs:complexType>

    <xs:complexType name="relationType">
        <xs:annotation>
            <xs:documentation>
                Amasty Custom Report Builder Relation Declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="xs:string" name="column" />
            <xs:element type="xs:string" name="reference_column" />
            <xs:element type="xs:string" name="relation_table" minOccurs="0" />
            <xs:element type="xs:string" name="relation_column" minOccurs="0" />
            <xs:element type="xs:string" name="relation_reference_column" minOccurs="0" />
            <xs:element type="xs:string" name="relationship_type" minOccurs="0" />
            <xs:element name="join_type" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="inner" />
                        <xs:enumeration value="left" />
                        <xs:enumeration value="right" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="expressionType">
        <xs:annotation>
            <xs:documentation>
                Amasty Custom Report Builder Expression Declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:annotation>
            <xs:documentation>
                Amasty Custom Report Builder Option Declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/ambuilder_entity_scheme/customer_address.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:amasty:module:Amasty_ReportBuilder:etc/entity_scheme.xsd">
    <amasty_report_builder_entities>
        <entity name="customer_address" eav="true">
            <title>Customer Address</title>
            <main_table>customer_address_entity</main_table>

            <columns>
                <column name="entity_id" primary="true" />
                <column name="region_id">
                    <source_model>Magento\Directory\Model\Config\Source\Allregion</source_model>
                </column>
                <column name="country_id">
                    <source_model>Magento\Directory\Model\Config\Source\Country</source_model>
                </column>
                <column name="is_active">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
            </columns>

            <relations>
                <relation name="customer" type="column">
                    <column>parent_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
                <relation name="order_address" type="column">
                    <column>entity_id</column>
                    <reference_column>customer_address_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
            </relations>
        </entity>
    </amasty_report_builder_entities>
</config>

=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/ambuilder_entity_scheme/customer.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:amasty:module:Amasty_ReportBuilder:etc/entity_scheme.xsd">
    <amasty_report_builder_entities>
        <entity name="customer" eav="true" primary="true">
            <title>Customer</title>
            <main_table>customer_entity</main_table>

            <columns>
                <column name="entity_id" primary="true" />
                <column name="created_at" useForPeriod="true" />
                <column name="group_id" columnType="default" />
                <column name="rp_token" columnType="default">
                    <hidden>true</hidden>
                </column>
                <column name="rp_token" columnType="default">
                    <hidden>true</hidden>
                </column>
                <column name="password_hash" columnType="default">
                    <hidden>true</hidden>
                </column>
                <column name="rp_token_created_at" columnType="default">
                    <hidden>true</hidden>
                </column>
                <column name="website_id" columnType="default">
                    <source_model>Amasty\ReportBuilder\Model\Source\Website</source_model>
                </column>
                <column name="group_id" columnType="default">
                    <source_model>Magento\Customer\Model\Customer\Source\Group</source_model>
                </column>
                <column name="is_active">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="disable_auto_group_change">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
            </columns>

            <relations>
                <relation name="customer_address" type="column">
                    <column>entity_id</column>
                    <reference_column>parent_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="order" type="column">
                    <column>entity_id</column>
                    <reference_column>customer_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="order_address" type="column">
                    <column>entity_id</column>
                    <reference_column>customer_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
            </relations>
        </entity>
    </amasty_report_builder_entities>
</config>

=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/ambuilder_entity_scheme/order.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:amasty:module:Amasty_ReportBuilder:etc/entity_scheme.xsd">
    <amasty_report_builder_entities>
        <entity name="order" primary="true">
            <title>Order Entity</title>
            <main_table>sales_order</main_table>

            <columns>
                <column name="entity_id" primary="true">
                    <title>Order ID</title>
                </column>
                <column name="increment_id">
                    <title>Order ID (Inc)</title>
                </column>
                <column name="store_id" frontendModel="multiselect">
                    <type>int</type>
                    <source_model>Magento\Store\Model\System\Store</source_model>
                </column>
                <column name="created_at" useForPeriod="true"/>
                <column name="status">
                    <source_model>Magento\Sales\Model\Config\Source\Order\Status</source_model>
                </column>
                <column name="is_virtual">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="protect_code">
                    <hidden>true</hidden>
                </column>
                <column name="can_ship_partially">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="can_ship_partially_item">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="customer_is_guest">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="customer_note_notify">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="email_sent">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="send_email">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="forced_shipment_with_invoice">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
            </columns>

            <relations>
                <relation name="order_item" type="column">
                    <column>entity_id</column>
                    <reference_column>order_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="order_address" type="column">
                    <column>entity_id</column>
                    <reference_column>parent_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="customer" type="column">
                    <column>customer_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
                <relation name="creditmemo" type="column">
                    <column>entity_id</column>
                    <reference_column>order_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="creditmemo" type="column">
                    <column>entity_id</column>
                    <reference_column>order_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="shipment" type="column">
                    <column>entity_id</column>
                    <reference_column>order_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
                <relation name="invoice" type="column">
                    <column>entity_id</column>
                    <reference_column>order_id</reference_column>
                    <relationship_type>one_to_many</relationship_type>
                </relation>
            </relations>
        </entity>
    </amasty_report_builder_entities>
</config>

=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/ambuilder_entity_scheme/creditmemo_item.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:amasty:module:Amasty_ReportBuilder:etc/entity_scheme.xsd">
    <amasty_report_builder_entities>
        <entity name="creditmemo_item">
            <title>Creditmemo Item</title>
            <main_table>sales_creditmemo_item</main_table>

            <columns>
                <column name="entity_id" primary="true" />
            </columns>

            <relations>
                <relation name="creditmemo" type="column">
                    <column>parent_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>many_to_one</relationship_type>
                </relation>
                <relation name="catalog_product" type="column">
                    <column>product_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
                <relation name="order_item" type="column">
                    <column>order_item_id</column>
                    <reference_column>item_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
            </relations>
        </entity>
    </amasty_report_builder_entities>
</config>

=== mateen009/TestProject/applatest/code/Amasty/ReportBuilder/etc/ambuilder_entity_scheme/order_address.xml
<?xml version="1.0"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:amasty:module:Amasty_ReportBuilder:etc/entity_scheme.xsd">
    <amasty_report_builder_entities>
        <entity name="order_address">
            <title>Order Address</title>
            <main_table>sales_order_address</main_table>

            <columns>
                <column name="entity_id" primary="true" />
                <column name="region_id">
                    <source_model>Magento\Directory\Model\Config\Source\Allregion</source_model>
                </column>
                <column name="country_id">
                    <source_model>Magento\Directory\Model\Config\Source\Country</source_model>
                </column>
                <column name="vat_is_valid">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
                <column name="vat_request_success">
                    <source_model>Magento\Config\Model\Config\Source\Yesno</source_model>
                </column>
            </columns>

            <relations>
                <relation name="order" type="column">
                    <column>parent_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
                <relation name="customer_address" type="column">
                    <column>customer_address_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
                <relation name="customer" type="column">
                    <column>customer_id</column>
                    <reference_column>entity_id</reference_column>
                    <relationship_type>one_to_one</relationship_type>
                </relation>
            </relations>
        </entity>
    </amasty_report_builder_entities>
</config>
